
STARTING DAFFE TESTS AT: Wed Apr  1 14:15:39 CEST 2015


RECORDS: 600000

NOTES:
- nsec values is database downtime
- min/sec value is migration duration
- Application starts and ends at DAFFE2


----------------------------------------
 DATA INCREMENT OF: 600000 records (4K)

2004.74 seconds init
----------------------------------------


----------------------------------------
 DEPLOYMENT: daffeflock-deployment4.yml
 IP ADDRESS: 54.145.165.251
----------------------------------------
MONGODB MIGRATION TIMINGS:
2277.38 seconds migration
72819466837 nsec DB downtime

MONGODB BYTES DIRECT: 2448669600
MONGODB COUNT DIRECT: 613943
MONGODB COUNT HTTP:   613943
MONGODB TIMES HTTP:   613943 count reported with connection timings:
    time_namelookup:  0.000
       time_connect:  0.117
    time_appconnect:  0.000
   time_pretransfer:  0.117
      time_redirect:  0.000
 time_starttransfer:  0.244
                    ----------
         time_total:  0.244
-----


----------------------------------------
 DEPLOYMENT: daffeflock-deployment5.yml
 IP ADDRESS: 54.177.53.81
----------------------------------------
MONGODB MIGRATION TIMINGS:
1783.38 seconds migration
36807171010 nsec DB downtime

MONGODB BYTES DIRECT: 2448919920
MONGODB COUNT DIRECT: 619158
MONGODB COUNT HTTP:   619158
MONGODB TIMES HTTP:   619158 count reported with connection timings:
    time_namelookup:  0.000
       time_connect:  0.176
    time_appconnect:  0.000
   time_pretransfer:  0.176
      time_redirect:  0.000
 time_starttransfer:  0.431
                    ----------
         time_total:  0.431
-----


----------------------------------------
 DEPLOYMENT: daffeflock-deployment6.yml
 IP ADDRESS: 175.41.186.101
----------------------------------------
MONGODB MIGRATION TIMINGS:
3050.35 seconds migration
48104992908 nsec DB downtime

MONGODB BYTES DIRECT: 2449244784
MONGODB COUNT DIRECT: 625926
MONGODB COUNT HTTP:   625926
MONGODB TIMES HTTP:   625926 count reported with connection timings:
    time_namelookup:  0.000
       time_connect:  0.355
    time_appconnect:  0.000
   time_pretransfer:  0.355
      time_redirect:  0.000
 time_starttransfer:  0.718
                    ----------
         time_total:  0.718
-----


----------------------------------------
 DEPLOYMENT: daffeflock-deployment3.yml
 IP ADDRESS: 54.74.144.100
----------------------------------------
MONGODB MIGRATION TIMINGS:
6239071086 nsec DB downtime
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flocker/volume/filesystems/zfs.py", line 596, in enumerate
    listing = _list_filesystems(self._reactor, self._name)
  File "/usr/lib/python2.7/site-packages/flocker/volume/filesystems/zfs.py", line 644, in _list_filesystems
    pool])
  File "/usr/lib/python2.7/site-packages/flocker/volume/filesystems/zfs.py", line 93, in zfs_command
    d = connectProtocol(endpoint, _AccumulatingProtocol())
  File "/usr/lib64/python2.7/site-packages/twisted/internet/endpoints.py", line 1783, in connectProtocol
    return endpoint.connect(OneShotFactory())
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/endpoints.py", line 424, in connect
    self._gid, self._usePTY, self._childFDs)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 345, in spawnProcess
    processProtocol, uid, gid, childFDs)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/process.py", line 677, in __init__
    self._fork(path, uid, gid, executable, args, environment, fdmap=fdmap)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/process.py", line 382, in _fork
    self.pid = os.fork()
exceptions.OSError: [Errno 12] Cannot allocate memory
main function encountered error
Traceback (most recent call last):
Failure: twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <type 'exceptions.OSError'>: [Errno 12] Cannot allocate memory
/usr/lib/python2.7/site-packages/flocker/volume/filesystems/zfs.py:596:enumerate
/usr/lib/python2.7/site-packages/flocker/volume/filesystems/zfs.py:644:_list_filesystems
/usr/lib/python2.7/site-packages/flocker/volume/filesystems/zfs.py:93:zfs_command
/usr/lib64/python2.7/site-packages/twisted/internet/endpoints.py:1783:connectProtocol
--- <exception caught here> ---
/usr/lib64/python2.7/site-packages/twisted/internet/endpoints.py:424:connect
/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py:345:spawnProcess
/usr/lib64/python2.7/site-packages/twisted/internet/process.py:677:__init__
/usr/lib64/python2.7/site-packages/twisted/internet/process.py:382:_fork
]]
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
--- <exception caught here> ---
  File "/home/thijs/Documents/Studie/LIA/flocker-tutorial/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 196, in _worker
    result = context.call(ctx, function, *args, **kwargs)
  File "/home/thijs/Documents/Studie/LIA/flocker-tutorial/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/thijs/Documents/Studie/LIA/flocker-tutorial/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/home/thijs/Documents/Studie/LIA/flocker-tutorial/local/lib/python2.7/site-packages/flocker/common/_ipc.py", line 90, in get_output
    raise IOError("Bad exit", remote_command, e.returncode, e.output)
exceptions.IOError: ('Bad exit', ['flocker-changestate', '"version": 1\n"nodes":\n#  "145.100.108.226": []\n#  "145.100.108.227": []\n  "54.74.144.100": ["mongodb", "daffedummy"]\n  "54.145.165.251": []\n  "54.177.53.81": []\n  "175.41.186.101": []\n\n', '"version": 1\n"applications":\n  "mongodb":\n    "image": "daffe/mongodb"\n    "ports":\n     - "internal": 27017\n       "external": 27017\n    "volume":\n      "mountpoint": "/data/db"\n  "daffedummy":\n    "image": "daffe/daffedummy"\n    "environment":\n       "TEST_VARIABLE": "DAFFE1337"\n    "links":\n     - "local_port": 27017\n       "remote_port": 27017\n       "alias": "mongo"\n    "ports":\n     - "internal": 8080\n       "external": 8080\n', '175.41.186.101:\n  applications:\n    daffedummy:\n      image: daffe/daffedummy:latest\n      ports:\n      - {external: 8080, internal: 8080}\n    mongodb:\n      image: daffe/mongodb:latest\n      ports:\n      - {external: 27017, internal: 27017}\n      volume: {mountpoint: /data/db}\n  used_ports: [22, 8080, 27017]\n  version: 1\n54.145.165.251:\n  applications: {}\n  used_ports: [22, 8080, 27017]\n  version: 1\n54.177.53.81:\n  applications: {}\n  used_ports: [22, 8080, 27017]\n  version: 1\n54.74.144.100:\n  applications: {}\n  used_ports: [22, 8080, 27017]\n  version: 1\n', '54.74.144.100'], 1, '')
19662.96 seconds migration

MONGODB BYTES DIRECT: Wed Apr  1 22:18:59.686 Error: couldn't connect to server 54.74.144.100:27017 at src/mongo/shell/mongo.js:147
MONGODB COUNT DIRECT: Wed Apr  1 22:18:59.754 Error: couldn't connect to server 54.74.144.100:27017 at src/mongo/shell/mongo.js:147
MONGODB COUNT HTTP:   
MONGODB TIMES HTTP:    count reported with connection timings:
    time_namelookup:  0.000
       time_connect:  0.000
    time_appconnect:  0.000
   time_pretransfer:  0.000
      time_redirect:  0.000
 time_starttransfer:  0.000
                    ----------
         time_total:  0.001
-----

DAFFE TESTS DONE AT: Wed Apr  1 22:18:59 CEST 2015

